[package]
name = "wormhole"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Windowing
winit = "0.28.6"

# Input
winit_input_helper = "0.14.1"
gilrs = "0.10.2"

# Graphics
wgpu = "0.17.0"
wgpu_glyph = "0.20.0"

# Shaders & math
bytemuck = "1.13.1"
crevice = { version = "0.13.0", features = ["glam"] }
glam = { version = "0.24.0", features = ["mint", "bytemuck"] }

# Asset loading
image = "0.24.7"

# futures (this exists because of the way wgpu works)
pollster = "0.3.0"

# general libraries
once_cell = "1.18"
